runtime: python39
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.9

env_variables:
  FIREBASE_API_KEY: AIzaSyAcvB_msyQ7g56SFgdWy5ijChaTUe-sMoI
  FIREBASE_PROJECT_ID: posturku-46f8e
